### PR TITLE
Use new REST JSON API for BulkSMS

### LINKED ISSUE #44: Use JSON REST API for BulkSMS
It seems that this package uses an outdated API for BulkSMS, they now have a new JSON REST API: https://www.bulksms.com/developer/json/v1/

### PR DESCRIPTION
**Pull request by denizdogan**
Breaking changes:

- `SENDSMS_BULKSMS_USERNAME` replaced by `SENDSMS_BULKSMS_TOKEN_ID`
- `SENDSMS_BULKSMS_PASSWORD` replaced by `SENDSMS_BULKSMS_TOKEN_SECRET`

Fixes #44

### CODE REVIEW

**Comment by denizdogan** [comment]
The tox suite is failing because of the Celery requirement probably not supporting Python 2.7

**Comment by stefanfoulis** [comment]
Thanks for this @denizdogan 🙇 

Does bulksms currently still support the old api?
(I am trying to figure out if we should release this with a bigger version bump because it is a breaking change, or if it is currently broken for bulksms anyway and this is basically a bugfix.)

**Comment by denizdogan** [comment]
@stefanfoulis The old API is deprecated and no longer actively worked on, but still works just fine. I haven't been able to find any information about when they're planning on shutting it off.

**Comment by stefanfoulis** [comment]
I rebased in #49 and merged.

**Pull request closed without merging**
